/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as VisionMaskImport } from './routes/vision-mask'
import { Route as SessionImport } from './routes/session'
import { Route as SceneImport } from './routes/scene'
import { Route as PubLabelsImport } from './routes/pub-labels'
import { Route as OneHundredImport } from './routes/one-hundred'
import { Route as FinderImport } from './routes/finder'
import { Route as AdminImport } from './routes/admin'
import { Route as AboutImport } from './routes/about'
import { Route as IndexImport } from './routes/index'
import { Route as ListsPubsImport } from './routes/lists/pubs'
import { Route as ListsAreasImport } from './routes/lists/areas'
import { Route as AreasSizerImport } from './routes/areas/sizer'
import { Route as AreasSimulatorImport } from './routes/areas/simulator'
import { Route as AreasIdentifierImport } from './routes/areas/identifier'

// Create/Update Routes

const VisionMaskRoute = VisionMaskImport.update({
  id: '/vision-mask',
  path: '/vision-mask',
  getParentRoute: () => rootRoute,
} as any)

const SessionRoute = SessionImport.update({
  id: '/session',
  path: '/session',
  getParentRoute: () => rootRoute,
} as any)

const SceneRoute = SceneImport.update({
  id: '/scene',
  path: '/scene',
  getParentRoute: () => rootRoute,
} as any)

const PubLabelsRoute = PubLabelsImport.update({
  id: '/pub-labels',
  path: '/pub-labels',
  getParentRoute: () => rootRoute,
} as any)

const OneHundredRoute = OneHundredImport.update({
  id: '/one-hundred',
  path: '/one-hundred',
  getParentRoute: () => rootRoute,
} as any)

const FinderRoute = FinderImport.update({
  id: '/finder',
  path: '/finder',
  getParentRoute: () => rootRoute,
} as any)

const AdminRoute = AdminImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRoute,
} as any)

const AboutRoute = AboutImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const ListsPubsRoute = ListsPubsImport.update({
  id: '/lists/pubs',
  path: '/lists/pubs',
  getParentRoute: () => rootRoute,
} as any)

const ListsAreasRoute = ListsAreasImport.update({
  id: '/lists/areas',
  path: '/lists/areas',
  getParentRoute: () => rootRoute,
} as any)

const AreasSizerRoute = AreasSizerImport.update({
  id: '/areas/sizer',
  path: '/areas/sizer',
  getParentRoute: () => rootRoute,
} as any)

const AreasSimulatorRoute = AreasSimulatorImport.update({
  id: '/areas/simulator',
  path: '/areas/simulator',
  getParentRoute: () => rootRoute,
} as any)

const AreasIdentifierRoute = AreasIdentifierImport.update({
  id: '/areas/identifier',
  path: '/areas/identifier',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutImport
      parentRoute: typeof rootRoute
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminImport
      parentRoute: typeof rootRoute
    }
    '/finder': {
      id: '/finder'
      path: '/finder'
      fullPath: '/finder'
      preLoaderRoute: typeof FinderImport
      parentRoute: typeof rootRoute
    }
    '/one-hundred': {
      id: '/one-hundred'
      path: '/one-hundred'
      fullPath: '/one-hundred'
      preLoaderRoute: typeof OneHundredImport
      parentRoute: typeof rootRoute
    }
    '/pub-labels': {
      id: '/pub-labels'
      path: '/pub-labels'
      fullPath: '/pub-labels'
      preLoaderRoute: typeof PubLabelsImport
      parentRoute: typeof rootRoute
    }
    '/scene': {
      id: '/scene'
      path: '/scene'
      fullPath: '/scene'
      preLoaderRoute: typeof SceneImport
      parentRoute: typeof rootRoute
    }
    '/session': {
      id: '/session'
      path: '/session'
      fullPath: '/session'
      preLoaderRoute: typeof SessionImport
      parentRoute: typeof rootRoute
    }
    '/vision-mask': {
      id: '/vision-mask'
      path: '/vision-mask'
      fullPath: '/vision-mask'
      preLoaderRoute: typeof VisionMaskImport
      parentRoute: typeof rootRoute
    }
    '/areas/identifier': {
      id: '/areas/identifier'
      path: '/areas/identifier'
      fullPath: '/areas/identifier'
      preLoaderRoute: typeof AreasIdentifierImport
      parentRoute: typeof rootRoute
    }
    '/areas/simulator': {
      id: '/areas/simulator'
      path: '/areas/simulator'
      fullPath: '/areas/simulator'
      preLoaderRoute: typeof AreasSimulatorImport
      parentRoute: typeof rootRoute
    }
    '/areas/sizer': {
      id: '/areas/sizer'
      path: '/areas/sizer'
      fullPath: '/areas/sizer'
      preLoaderRoute: typeof AreasSizerImport
      parentRoute: typeof rootRoute
    }
    '/lists/areas': {
      id: '/lists/areas'
      path: '/lists/areas'
      fullPath: '/lists/areas'
      preLoaderRoute: typeof ListsAreasImport
      parentRoute: typeof rootRoute
    }
    '/lists/pubs': {
      id: '/lists/pubs'
      path: '/lists/pubs'
      fullPath: '/lists/pubs'
      preLoaderRoute: typeof ListsPubsImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/finder': typeof FinderRoute
  '/one-hundred': typeof OneHundredRoute
  '/pub-labels': typeof PubLabelsRoute
  '/scene': typeof SceneRoute
  '/session': typeof SessionRoute
  '/vision-mask': typeof VisionMaskRoute
  '/areas/identifier': typeof AreasIdentifierRoute
  '/areas/simulator': typeof AreasSimulatorRoute
  '/areas/sizer': typeof AreasSizerRoute
  '/lists/areas': typeof ListsAreasRoute
  '/lists/pubs': typeof ListsPubsRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/finder': typeof FinderRoute
  '/one-hundred': typeof OneHundredRoute
  '/pub-labels': typeof PubLabelsRoute
  '/scene': typeof SceneRoute
  '/session': typeof SessionRoute
  '/vision-mask': typeof VisionMaskRoute
  '/areas/identifier': typeof AreasIdentifierRoute
  '/areas/simulator': typeof AreasSimulatorRoute
  '/areas/sizer': typeof AreasSizerRoute
  '/lists/areas': typeof ListsAreasRoute
  '/lists/pubs': typeof ListsPubsRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/finder': typeof FinderRoute
  '/one-hundred': typeof OneHundredRoute
  '/pub-labels': typeof PubLabelsRoute
  '/scene': typeof SceneRoute
  '/session': typeof SessionRoute
  '/vision-mask': typeof VisionMaskRoute
  '/areas/identifier': typeof AreasIdentifierRoute
  '/areas/simulator': typeof AreasSimulatorRoute
  '/areas/sizer': typeof AreasSizerRoute
  '/lists/areas': typeof ListsAreasRoute
  '/lists/pubs': typeof ListsPubsRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/finder'
    | '/one-hundred'
    | '/pub-labels'
    | '/scene'
    | '/session'
    | '/vision-mask'
    | '/areas/identifier'
    | '/areas/simulator'
    | '/areas/sizer'
    | '/lists/areas'
    | '/lists/pubs'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/admin'
    | '/finder'
    | '/one-hundred'
    | '/pub-labels'
    | '/scene'
    | '/session'
    | '/vision-mask'
    | '/areas/identifier'
    | '/areas/simulator'
    | '/areas/sizer'
    | '/lists/areas'
    | '/lists/pubs'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/finder'
    | '/one-hundred'
    | '/pub-labels'
    | '/scene'
    | '/session'
    | '/vision-mask'
    | '/areas/identifier'
    | '/areas/simulator'
    | '/areas/sizer'
    | '/lists/areas'
    | '/lists/pubs'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRoute
  FinderRoute: typeof FinderRoute
  OneHundredRoute: typeof OneHundredRoute
  PubLabelsRoute: typeof PubLabelsRoute
  SceneRoute: typeof SceneRoute
  SessionRoute: typeof SessionRoute
  VisionMaskRoute: typeof VisionMaskRoute
  AreasIdentifierRoute: typeof AreasIdentifierRoute
  AreasSimulatorRoute: typeof AreasSimulatorRoute
  AreasSizerRoute: typeof AreasSizerRoute
  ListsAreasRoute: typeof ListsAreasRoute
  ListsPubsRoute: typeof ListsPubsRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRoute,
  FinderRoute: FinderRoute,
  OneHundredRoute: OneHundredRoute,
  PubLabelsRoute: PubLabelsRoute,
  SceneRoute: SceneRoute,
  SessionRoute: SessionRoute,
  VisionMaskRoute: VisionMaskRoute,
  AreasIdentifierRoute: AreasIdentifierRoute,
  AreasSimulatorRoute: AreasSimulatorRoute,
  AreasSizerRoute: AreasSizerRoute,
  ListsAreasRoute: ListsAreasRoute,
  ListsPubsRoute: ListsPubsRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/about",
        "/admin",
        "/finder",
        "/one-hundred",
        "/pub-labels",
        "/scene",
        "/session",
        "/vision-mask",
        "/areas/identifier",
        "/areas/simulator",
        "/areas/sizer",
        "/lists/areas",
        "/lists/pubs"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/about": {
      "filePath": "about.tsx"
    },
    "/admin": {
      "filePath": "admin.tsx"
    },
    "/finder": {
      "filePath": "finder.tsx"
    },
    "/one-hundred": {
      "filePath": "one-hundred.tsx"
    },
    "/pub-labels": {
      "filePath": "pub-labels.tsx"
    },
    "/scene": {
      "filePath": "scene.tsx"
    },
    "/session": {
      "filePath": "session.tsx"
    },
    "/vision-mask": {
      "filePath": "vision-mask.tsx"
    },
    "/areas/identifier": {
      "filePath": "areas/identifier.tsx"
    },
    "/areas/simulator": {
      "filePath": "areas/simulator.tsx"
    },
    "/areas/sizer": {
      "filePath": "areas/sizer.tsx"
    },
    "/lists/areas": {
      "filePath": "lists/areas.tsx"
    },
    "/lists/pubs": {
      "filePath": "lists/pubs.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
